// ======================================================
// BLACKBOX LAB — ONE-FILE REPORT BUILDER
// ======================================================
//
// Builds a single self-contained HTML file: verdict,
// lab findings and chart images embedded as data URLs.
// Works on any forum, chat or email — no server, no
// account, nothing to install.
//
// ======================================================

function chartImage(element) {
  const canvas = element?.querySelector("canvas");

  if (!canvas) {
    return null;
  }

  try {
    return canvas.toDataURL("image/png");
  } catch {
    return null;
  }
}

function statusColor(status) {
  if (status === "attention") return "#c0392b";
  if (status === "watch") return "#b9770e";
  return "#1e8449";
}

function statusWord(status) {
  if (status === "attention") return "NEEDS ATTENTION";
  if (status === "watch") return "WORTH WATCHING";
  return "LOOKS GOOD";
}

export function buildReportHtml({
  fileName,
  craftName,
  firmware,
  durationSeconds,
  verdict,
  labs,
  chartElements
}) {
  const date = new Date().toLocaleString();

  const cardsHtml = (verdict?.cards ?? [])
    .map(
      (card) => `
      <div style="border:1px solid #ddd;border-left:6px solid ${statusColor(card.status)};border-radius:6px;padding:12px 16px;margin:10px 0;">
        <div style="font-size:12px;letter-spacing:1px;color:${statusColor(card.status)};font-weight:bold;">${card.title.toUpperCase()} — ${statusWord(card.status)}</div>
        <div style="font-size:16px;font-weight:bold;margin:4px 0;">${card.headline}</div>
        <div style="color:#444;">${card.detail}</div>
        <div style="color:#888;font-size:12px;margin-top:4px;">Evidence: ${card.evidence}</div>
      </div>`
    )
    .join("");

  const labsHtml = (labs ?? [])
    .filter((lab) => lab && lab.analysis)
    .map((lab) => {
      const metrics = lab.analysis.metrics
        .map(
          (metric) => `
          <tr>
            <td style="padding:4px 12px 4px 0;color:#666;">${metric.label}</td>
            <td style="padding:4px 0;font-weight:bold;">${metric.value}</td>
          </tr>`
        )
        .join("");

      return `
      <h3 style="margin:22px 0 6px 0;">${lab.title}</h3>
      <p style="margin:0 0 8px 0;color:#333;">${lab.analysis.story}</p>
      <table style="border-collapse:collapse;font-size:14px;">${metrics}</table>`;
    })
    .join("");

  const chartsHtml = (chartElements ?? [])
    .map(({ title, element }) => {
      const image = chartImage(element);

      return image
        ? `<h3 style="margin:22px 0 6px 0;">${title}</h3>
           <img src="${image}" style="max-width:100%;border:1px solid #eee;border-radius:6px;" alt="${title}" />`
        : "";
    })
    .join("");

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Blackbox Lab Report — ${fileName}</title>
</head>
<body style="font-family:Segoe UI,Arial,sans-serif;max-width:820px;margin:24px auto;padding:0 16px;color:#111;">
  <div style="border-bottom:3px solid #16324f;padding-bottom:10px;">
    <div style="font-size:22px;font-weight:bold;">Blackbox Lab — Flight Report</div>
    <div style="color:#555;margin-top:4px;">
      ${craftName ? `Craft: <b>${craftName}</b> · ` : ""}${firmware ? `${firmware} · ` : ""}Flight length: ${durationSeconds ? durationSeconds.toFixed(1) + " s" : "n/a"}<br>
      Log: ${fileName} · Generated ${date}
    </div>
  </div>

  <h2 style="margin:20px 0 4px 0;">Verdict</h2>
  <p style="margin:0;color:#333;">${verdict?.summary ?? ""}</p>
  ${cardsHtml}

  <h2 style="margin:26px 0 0 0;">Lab Details</h2>
  ${labsHtml}

  <h2 style="margin:26px 0 0 0;">Charts</h2>
  ${chartsHtml}

  <p style="color:#999;font-size:12px;margin-top:28px;border-top:1px solid #eee;padding-top:10px;">
    Generated by Blackbox Lab — free Rotorflight log analysis.
    Values marked (est.) are estimated from logged raw data.
    Blackbox Lab never changes any settings; every decision is the pilot's.
  </p>
</body>
</html>`;
}

export function downloadReport(html, fileName) {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();

  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
